- hosts: localhost
  connection: local
  tasks:
    - name: Stop old container
      community.docker.docker_container:
        name: mini-calculator
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: mini-calculator
        image: mini-calculator:latest
        ports:
          - "8081:8080"
